/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Flow {
    'id'?: any | null;
    'created'?: any | null;
    'userId'?: any | null;
    'steps'?: any | null;
    'completedSteps'?: any | null;
    'link'?: any | null;
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "any"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "any"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "any"
        },
        {
            "name": "completedSteps",
            "baseName": "completed_steps",
            "type": "any"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return Flow.attributeTypeMap;
    }
}

