/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PaymentMethod {
    'id'?: any | null;
    'platform': PaymentMethod.PlatformEnum;
    'description'?: any | null;
    'mask'?: any | null;
    'email'?: any | null;
    'phoneNumber'?: any | null;
    'cashTag'?: any | null;
    'country'?: any | null;
    'currency'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PaymentMethod.PlatformEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "any"
        },
        {
            "name": "mask",
            "baseName": "mask",
            "type": "any"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "any"
        },
        {
            "name": "cashTag",
            "baseName": "cash_tag",
            "type": "any"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "any"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethod.attributeTypeMap;
    }
}

export namespace PaymentMethod {
    export enum PlatformEnum {
        Ach = <any> 'ach',
        Paypal = <any> 'paypal',
        Venmo = <any> 'venmo',
        CashApp = <any> 'cash_app',
        IntlTransfer = <any> 'intl_transfer'
    }
}
