/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PayoutLinkDelivery {
    'method'?: PayoutLinkDelivery.MethodEnum;
    'email'?: any | null;
    'countryCode'?: any | null;
    'phoneNumber'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "PayoutLinkDelivery.MethodEnum"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any"
        },
        {
            "name": "countryCode",
            "baseName": "country_code",
            "type": "any"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PayoutLinkDelivery.attributeTypeMap;
    }
}

export namespace PayoutLinkDelivery {
    export enum MethodEnum {
        Link = <any> 'link',
        Sms = <any> 'sms',
        Email = <any> 'email'
    }
}
