/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PayoutLinkDelivery } from './payoutLinkDelivery';
import { PayoutLinkPayee } from './payoutLinkPayee';

export class PayoutLink {
    'id'?: any | null;
    'created'?: any | null;
    'link'?: any | null;
    'amount'?: any | null;
    'status'?: PayoutLink.StatusEnum;
    'payee'?: PayoutLinkPayee;
    'delivery'?: PayoutLinkDelivery;
    'taxExempt'?: any | null;
    'claimedUserId'?: any | null;
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "any"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "any"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "any"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PayoutLink.StatusEnum"
        },
        {
            "name": "payee",
            "baseName": "payee",
            "type": "PayoutLinkPayee"
        },
        {
            "name": "delivery",
            "baseName": "delivery",
            "type": "PayoutLinkDelivery"
        },
        {
            "name": "taxExempt",
            "baseName": "tax_exempt",
            "type": "any"
        },
        {
            "name": "claimedUserId",
            "baseName": "claimed_user_id",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PayoutLink.attributeTypeMap;
    }
}

export namespace PayoutLink {
    export enum StatusEnum {
        Claimed = <any> 'claimed',
        DeliveryPending = <any> 'delivery_pending',
        DeliveryFailed = <any> 'delivery_failed',
        Delivered = <any> 'delivered',
        Canceled = <any> 'canceled'
    }
}
