/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostV2PayoutsSendPayoutRequestDelivery } from './postV2PayoutsSendPayoutRequestDelivery';
import { PostV2PayoutsSendPayoutRequestPayee } from './postV2PayoutsSendPayoutRequestPayee';

export class PostV2PayoutsSendPayoutRequest {
    /**
    * The amount in cents to pay the user.
    */
    'amount': any | null;
    /**
    * The user\'s id. `user_id` or `payee` is required.
    */
    'userId'?: any | null;
    'payee'?: PostV2PayoutsSendPayoutRequestPayee;
    'delivery'?: PostV2PayoutsSendPayoutRequestDelivery;
    /**
    * Collect 1099 or w8-ben information.
    */
    'forceCollectComplianceInformation'?: any | null;
    /**
    * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "any"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "any"
        },
        {
            "name": "payee",
            "baseName": "payee",
            "type": "PostV2PayoutsSendPayoutRequestPayee"
        },
        {
            "name": "delivery",
            "baseName": "delivery",
            "type": "PostV2PayoutsSendPayoutRequestDelivery"
        },
        {
            "name": "forceCollectComplianceInformation",
            "baseName": "force_collect_compliance_information",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PostV2PayoutsSendPayoutRequest.attributeTypeMap;
    }
}

