/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PostTransfersRequest {
    /**
    * The amount in cents to transfer. Negative amount transfers money from the `app` to the `user`.
    */
    'amount': any | null;
    /**
    * The user\'s id.
    */
    'userId': any | null;
    /**
    * Transfers marked as `tax_exempt` will not be counted towards the 1099 threshold.
    */
    'taxExempt'?: any | null;
    'idempotencyKey'?: any | null;
    /**
    * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "any"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "any"
        },
        {
            "name": "taxExempt",
            "baseName": "tax_exempt",
            "type": "any"
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PostTransfersRequest.attributeTypeMap;
    }
}

