/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PostV2FlowsRequest {
    /**
    * A list of steps.
    */
    'steps': Set<PostV2FlowsRequest.StepsEnum>;
    /**
    * The user\'s id.
    */
    'userId'?: any | null;
    /**
    * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Set<PostV2FlowsRequest.StepsEnum>"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PostV2FlowsRequest.attributeTypeMap;
    }
}

export namespace PostV2FlowsRequest {
    export enum StepsEnum {
        Compliance = <any> 'compliance',
        ManagePayouts = <any> 'manage-payouts',
        ManagePayments = <any> 'manage-payments',
        Payout = <any> 'payout'
    }
}
