/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The payee. This is optional.
*/
export class PostV2PayoutLinksRequestPayee {
    'firstName'?: any | null;
    'lastName'?: any | null;
    'countryCode'?: any | null;
    'phoneNumber'?: any | null;
    'email'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "any"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "any"
        },
        {
            "name": "countryCode",
            "baseName": "country_code",
            "type": "any"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "any"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PostV2PayoutLinksRequestPayee.attributeTypeMap;
    }
}

