/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PostV2PayoutLinksRequestDelivery {
    'message'?: any | null;
    /**
    * Delivery method. `sms` requires `payee.country_code` and `payee.phone_number`, `email` required `payee.email`.
    */
    'method'?: PostV2PayoutLinksRequestDelivery.MethodEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "any"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "PostV2PayoutLinksRequestDelivery.MethodEnum"
        }    ];

    static getAttributeTypeMap() {
        return PostV2PayoutLinksRequestDelivery.attributeTypeMap;
    }
}

export namespace PostV2PayoutLinksRequestDelivery {
    export enum MethodEnum {
        Sms = <any> 'sms',
        Link = <any> 'link',
        Email = <any> 'email'
    }
}
