/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostV2PayoutLinksRequestDelivery } from './postV2PayoutLinksRequestDelivery';
import { PostV2PayoutLinksRequestPayee } from './postV2PayoutLinksRequestPayee';

export class PostV2PayoutLinksRequest {
    /**
    * The user\'s id.
    */
    'userId'?: any | null;
    'payee'?: PostV2PayoutLinksRequestPayee;
    'amount': any | null;
    'delivery'?: PostV2PayoutLinksRequestDelivery;
    /**
    * Force the collection of 1099 or W-8 information. Defaults to `false`.
    */
    'forceCollectComplianceInformation'?: any | null;
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "any"
        },
        {
            "name": "payee",
            "baseName": "payee",
            "type": "PostV2PayoutLinksRequestPayee"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "any"
        },
        {
            "name": "delivery",
            "baseName": "delivery",
            "type": "PostV2PayoutLinksRequestDelivery"
        },
        {
            "name": "forceCollectComplianceInformation",
            "baseName": "force_collect_compliance_information",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PostV2PayoutLinksRequest.attributeTypeMap;
    }
}

