/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PutUsersUserIdPayoutMethodsRequest {
    /**
    * Payout platform to add.
    */
    'platform': PutUsersUserIdPayoutMethodsRequest.PlatformEnum;
    /**
    * Bank account or Cash App routing number. Required if `platform` = `ach` or `cash_app`.
    */
    'routingNumber'?: any | null;
    /**
    * Bank account or Cash App account number. Required if `platform` = `ach` or `cash_app`.
    */
    'accountNumber'?: any | null;
    /**
    * Bank account type. Required if `platform` = `ach`.
    */
    'accountType'?: PutUsersUserIdPayoutMethodsRequest.AccountTypeEnum;
    /**
    * PayPal email address. Required if `platform` = `paypal`.
    */
    'email'?: any | null;
    /**
    * Venmo phone number. Required if `platform` = `venmo`.
    */
    'phoneNumber'?: any | null;
    /**
    * Cash App Cash Tag. Required if `platform` = `cash_app`.
    */
    'cashTag'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PutUsersUserIdPayoutMethodsRequest.PlatformEnum"
        },
        {
            "name": "routingNumber",
            "baseName": "routing_number",
            "type": "any"
        },
        {
            "name": "accountNumber",
            "baseName": "account_number",
            "type": "any"
        },
        {
            "name": "accountType",
            "baseName": "account_type",
            "type": "PutUsersUserIdPayoutMethodsRequest.AccountTypeEnum"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "any"
        },
        {
            "name": "cashTag",
            "baseName": "cash_tag",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PutUsersUserIdPayoutMethodsRequest.attributeTypeMap;
    }
}

export namespace PutUsersUserIdPayoutMethodsRequest {
    export enum PlatformEnum {
        Paypal = <any> 'paypal',
        Venmo = <any> 'venmo',
        CashApp = <any> 'cash_app',
        Ach = <any> 'ach'
    }
    export enum AccountTypeEnum {
        Checking = <any> 'checking',
        Savings = <any> 'savings'
    }
}
