/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PutV2UsersUserIdKycRequestAddress {
    'line1': any | null;
    'line2'?: any | null;
    'city': any | null;
    'state': any | null;
    'country': any | null;
    'postcode': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "line1",
            "baseName": "line_1",
            "type": "any"
        },
        {
            "name": "line2",
            "baseName": "line_2",
            "type": "any"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "any"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "any"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "any"
        },
        {
            "name": "postcode",
            "baseName": "postcode",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PutV2UsersUserIdKycRequestAddress.attributeTypeMap;
    }
}

