/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PutV2UsersUserIdKycRequestAddress } from './putV2UsersUserIdKycRequestAddress';

export class PutV2UsersUserIdKycRequest {
    'entityType': PutV2UsersUserIdKycRequest.EntityTypeEnum;
    /**
    * Legal bussiness name. Required if `entity_type` is business.
    */
    'businessName'?: any | null;
    /**
    * SSN if `entity_type` is `individual`. EIN if `entity_type` is `business`.
    */
    'tin': any | null;
    'address': PutV2UsersUserIdKycRequestAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "PutV2UsersUserIdKycRequest.EntityTypeEnum"
        },
        {
            "name": "businessName",
            "baseName": "business_name",
            "type": "any"
        },
        {
            "name": "tin",
            "baseName": "tin",
            "type": "any"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "PutV2UsersUserIdKycRequestAddress"
        }    ];

    static getAttributeTypeMap() {
        return PutV2UsersUserIdKycRequest.attributeTypeMap;
    }
}

export namespace PutV2UsersUserIdKycRequest {
    export enum EntityTypeEnum {
        Individual = <any> 'individual',
        Business = <any> 'business'
    }
}
