/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransferExternalData } from './transferExternalData';

export class Transfer {
    'id'?: any | null;
    'created'?: any | null;
    'userId'?: any | null;
    'status'?: Transfer.StatusEnum;
    'type'?: Transfer.TypeEnum;
    'amount'?: any | null;
    'externalData'?: TransferExternalData;
    'transactions'?: any | null;
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "any"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "any"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Transfer.StatusEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Transfer.TypeEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "any"
        },
        {
            "name": "externalData",
            "baseName": "external_data",
            "type": "TransferExternalData"
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "any"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return Transfer.attributeTypeMap;
    }
}

export namespace Transfer {
    export enum StatusEnum {
        Created = <any> 'created',
        Pending = <any> 'pending',
        Failed = <any> 'failed',
        Completed = <any> 'completed',
        Flagged = <any> 'flagged'
    }
    export enum TypeEnum {
        Refill = <any> 'refill',
        Payout = <any> 'payout',
        Balance = <any> 'balance'
    }
}
