/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TransferExternalData {
    'accountId'?: any | null;
    'externalId'?: any | null;
    'platform'?: TransferExternalData.PlatformEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "any"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "any"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "TransferExternalData.PlatformEnum"
        }    ];

    static getAttributeTypeMap() {
        return TransferExternalData.attributeTypeMap;
    }
}

export namespace TransferExternalData {
    export enum PlatformEnum {
        Ach = <any> 'ach',
        Paypal = <any> 'paypal',
        Venmo = <any> 'venmo',
        Visa = <any> 'visa',
        Amazon = <any> 'amazon',
        CashApp = <any> 'cash_app',
        IntlBank = <any> 'intl_bank',
        IntlTransfer = <any> 'intl_transfer',
        BankTransfer = <any> 'bank_transfer'
    }
}
