/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserCompliance } from './userCompliance';
import { UserPhoneNumber } from './userPhoneNumber';
import { Wallet } from './wallet';

export class User {
    'id'?: any | null;
    'firstName'?: any | null;
    'lastName'?: any | null;
    'email'?: any | null;
    'phoneNumber'?: UserPhoneNumber;
    'wallet'?: Wallet;
    'compliance'?: UserCompliance;
    'metadata'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "any"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "any"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "UserPhoneNumber"
        },
        {
            "name": "wallet",
            "baseName": "wallet",
            "type": "Wallet"
        },
        {
            "name": "compliance",
            "baseName": "compliance",
            "type": "UserCompliance"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

