/**
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserCompliance {
    'taxIdCollected'?: any | null;
    'addressCollected'?: any | null;
    'dateOfBirthCollected'?: any | null;
    '_1099collected'?: any | null;
    'w8BenCollected'?: any | null;
    'flagged'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taxIdCollected",
            "baseName": "tax_id_collected",
            "type": "any"
        },
        {
            "name": "addressCollected",
            "baseName": "address_collected",
            "type": "any"
        },
        {
            "name": "dateOfBirthCollected",
            "baseName": "date_of_birth_collected",
            "type": "any"
        },
        {
            "name": "_1099collected",
            "baseName": "1099_collected",
            "type": "any"
        },
        {
            "name": "w8BenCollected",
            "baseName": "w8_ben_collected",
            "type": "any"
        },
        {
            "name": "flagged",
            "baseName": "flagged",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return UserCompliance.attributeTypeMap;
    }
}

